version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - connection

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      BACKEND_DNS: backend
      BACKEND_PORT: 9000
    depends_on:
      - backend
    networks:
      - connection

  tester:
    image: curlimages/curl:8.8.0
    depends_on:
      - frontend
    networks:
      - connection
    volumes:
      - ./test-app.sh:/test-app.sh:ro
    entrypoint: ["sh", "/test-app.sh", "http://frontend:8080/healthz"]


networks:
  connection:
