services:
  backend:
    image: ghcr.io/strikzie/slow-and-steady-wins-the-race:latest
    ports:
      - "9000:9000"
    networks:
      - connection

  frontend:
    image: ghcr.io/strikzie/fortune-favors-the-bold:latest
    ports:
      - "8080:8080"
    environment:
      BACKEND_DNS: backend
      BACKEND_PORT: 9000
    depends_on:
      - backend
    networks:
      - connection

networks:
  connection:
