version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerfileBackend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileFrontend
    ports:
      - "8080:8080"
    depends_on:
      backend:
        condition: service_healthy