apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-deployment
spec:
  selector:
    app: backend-deployment
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000 
  type: ClusterIP
