apiVersion: v1
kind: Service

metadata:
  name: frontend-service
  labels:
    app: frontend-deployment

spec:
  selector:
    app: frontend-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
