name: docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build frontend Docker image
      run: |
        IMAGE_NAME=ghcr.io/strikzie/fortune-favors-the-bold:latest
        docker build -t $IMAGE_NAME ./frontend

    - name: Push frontend Docker image
      run: |
        IMAGE_NAME=ghcr.io/strikzie/fortune-favors-the-bold:latest
        docker push $IMAGE_NAME

    - name: Build backend Docker image
      run: |
        IMAGE_NAME=ghcr.io/strikzie/slow-and-steady-wins-the-race:latest
        docker build -t $IMAGE_NAME ./backend

    - name: Push backend Docker image
      run: |
        IMAGE_NAME=ghcr.io/strikzie/slow-and-steady-wins-the-race:latest
        docker push $IMAGE_NAME

    - name: Run Docker Compose for tests
      run: docker compose -f docker-compose.yml up --build --abort-on-container-exit

    - name: Cleanup
      if: always()
      run: docker compose -f docker-compose.yml down -v
